version: "3.9"
services:
  jenkins:
    container_name: jenkins
    image: jenkins
    restart: unless-stopped
    privileged: true
    user: root
    environment:
      - TZ=Asia/Kuala_Lumpur
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    build: 
      context: .
      dockerfile: Dockerfile.jenkins